language: ruby
dist: bionic
sudo: false
cache: bundler
script: bundle exec rspec
bundler_args: --without=extras
before_script:
  - bundle exec sidekiq -r ./spec/dummy_app/app.rb -L /tmp/sidekiq.log &
  - sleep 1
services:
  - redis-server
rvm:
  - 2.5.9
  - 2.6.10
  - 2.7.7
  - 3.0.5
  - 3.1.2
  - 3.2.0
  - jruby-9.2.9.0
